{
 "title": "TIBCO FTL & EMS Licensing",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "RV License Expiration Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tibco_rv_license_expiration_seconds",
     "legendFormat": "RV - {{instance}}"
    }
   ]
  },
  {
   "title": "EMS License Expiration Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (tibco_ems_server_license_expiration_seconds)",
     "legendFormat": "EMS - {{instance}}"
    }
   ]
  },
  {
   "title": "FTL License Expiration Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (tibco_ftl_server_license_expiration_seconds)",
     "legendFormat": "FTL - {{instance}}"
    }
   ]
  }
 ]
}